# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [17]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [18]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [19]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [20]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [21]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [24]:
print(np.arange(20,36,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [25]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [26]:
print('\n---Results of a([1,2,3]) and b([4,5,6])')


---Results of a([1,2,3]) and b([4,5,6])


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [27]:
import pandas as pd


In [31]:
import pandas as pd
record = {"name":["nivetha","lakshmi"],"marks":["35","35"],"status":["pass","pass"]}
df = pd.DataFrame(record)                                                                     
df

name marks status
0  nivetha    35   pass
1  lakshmi    35   pass

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [2]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [3]:
lists = {"s.no":[1,2,3], "name":['aaa','bbb','ccc'], "value":[22,25,24]}

In [5]:
pd.DataFrame(lists)

NameError: name 'pd' is not defined